### ISSUE TITLE
Placeholder header on the paper

### ISSUE THREAD

**Issue by KaruroChori** [galatolofederico/cerbero-7b#1]
![image](https://github.com/galatolofederico/cerbero-7b/assets/9377545/25b407dd-3dfd-40ca-860c-671687fda98f)

You might want to remove the header from the demo project before publishing :).

**Comment by galatolofederico** [comment]
Thank you for the suggestion. The paper is currently undergoing peer review. I don't mind having the template placeholder on the preprint at this stage. Once the review process is complete, I'll make the final polish. After all, preprints are called 'pre-prints' for a reason, aren't they? :smiley:

**Comment by KaruroChori** [comment]
Fair enough :D
